services:
  - type: web
    name: foreignfinds
    runtime: php
    region: oregon
    plan: free
    phpVersion: 8.3
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
